name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo MYSQL_HOST=${{ secrets.MYSQL_HOST }} >> $GITHUB_ENV
          echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> $GITHUB_ENV
          echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> $GITHUB_ENV
          echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> $GITHUB_ENV
          echo DB_PORT=${{ secrets.DB_PORT }} >> $GITHUB_ENV
          echo ACCESS_KEY=${{ secrets.ACCESS_KEY }} >> $GITHUB_ENV
          echo SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }} >> $GITHUB_ENV
          echo RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }} >> $GITHUB_ENV
          echo RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }} >> $GITHUB_ENV

      - name: Build and Test
        run: |
          npm install
          docker-compose up --build -d
          docker-compose run --rm node-service npm run test
          docker-compose down

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-service:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-service:latest

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: build_and_push_docker
    steps:
      - name: Execute remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/node-service:latest
            docker stop node-service || true
            docker rm node-service || true
            docker run --name node-service -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/node-service:latest
